# Generated by Django 4.0.6 on 2022-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_activerecipe_activeblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeblog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activeblog',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activerecipe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activerecipe',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
