# Generated by Django 4.0.6 on 2022-10-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_activeblog_date_activeblog_is_seen_activerecipe_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Comment')]),
        ),
    ]
