# Generated by Django 4.0.6 on 2022-10-18 21:58

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_remove_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', django_quill.fields.QuillField()),
                ('image', models.ImageField(default='Blog/default.png', null=True, upload_to='Blog')),
                ('isActive', models.BooleanField(default=False)),
                ('inSlide', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogown', to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
