# Generated by Django 4.0.6 on 2022-09-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cook_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.CharField(choices=[('sn', 'sn'), ('deq', 'deq'), ('s', 's'), ('g', 'g')], default='deq', max_length=10, null=True),
        ),
    ]
