# Generated by Django 4.0.6 on 2022-09-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_category_image'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='blog',
            order_with_respect_to='created',
        ),
    ]
