# Generated by Django 4.0.6 on 2022-09-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blog_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='blog',
            order_with_respect_to=None,
        ),
    ]
