# Generated by Django 4.0.6 on 2022-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_blog_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
