# Generated by Django 4.0.6 on 2022-09-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blog_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/default.jpg', null=True, upload_to='Blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
