# Generated by Django 4.0.6 on 2022-09-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_email'),
        ('blog', '0021_remove_blog_cook_time_remove_blog_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogown', to='users.profile'),
        ),
    ]
