# Generated by Django 4.0.6 on 2022-09-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='Blog/default.png', null=True, upload_to='Blog'),
        ),
    ]
