# Generated by Django 4.0.6 on 2022-10-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blog_options_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='inSlide',
            field=models.BooleanField(default=False),
        ),
    ]
