# Generated by Django 4.0.6 on 2022-10-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_subscribedusers_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedusers',
            options={'ordering': ['-created_date'], 'verbose_name': 'Email İzləyici', 'verbose_name_plural': 'Email İzləyicilər'},
        ),
    ]
