# Generated by Django 4.0.6 on 2022-09-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='blog/default.jpg', null=True, upload_to='Blog')),
                ('isActive', models.BooleanField(default=True)),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug')),
                ('cook_time', models.IntegerField(null=True)),
                ('time', models.CharField(choices=[('saniyə', 'saniyə'), ('dəqiqə', 'dəqiqə'), ('saat', 'saat'), ('gün', 'gün')], default='dəqiqə', max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'up vote'), ('down', 'down vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogreview', to='recipes.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category'),
        ),
    ]
