# Generated by Django 4.0.6 on 2022-09-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog/default.jpg', null=True, upload_to='Recipes'),
        ),
    ]
