# Generated by Django 4.0.6 on 2022-09-29 21:29

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
