# Generated by Django 4.0.6 on 2022-09-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_blog_youtube_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='Recipes/default.jpg', null=True, upload_to='Recipes'),
        ),
    ]
