# Generated by Django 4.0.6 on 2022-10-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_vote_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
    ]
