# Generated by Django 4.0.6 on 2022-10-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_review_unique_together_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='votes',
        ),
    ]
