# Generated by Django 4.0.6 on 2022-10-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_email'),
        ('recipes', '0008_remove_blog_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.blog'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('owner', 'recipe')},
        ),
    ]
