# Generated by Django 4.0.6 on 2022-10-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_vote_recipe_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.blog'),
        ),
    ]
