# Generated by Django 4.0.6 on 2022-10-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_review_options_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
