# Generated by Django 4.0.6 on 2022-10-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebook',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.blog', unique=True),
        ),
    ]
