# Generated by Django 4.0.6 on 2022-10-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipebook_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebook',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.blog'),
        ),
    ]
