# Generated by Django 4.0.6 on 2022-10-05 04:49

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_email'),
        ('recipes', '0015_alter_recipebook_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created'], 'verbose_name': 'Resept', 'verbose_name_plural': 'Reseptlər'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category', verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cook_time',
            field=models.IntegerField(null=True, verbose_name='Bişirilmə Vaxtı'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaradılma Vaxtı'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='Recipes/default.jpg', null=True, upload_to='Recipes', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Aktivlik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile', verbose_name='Postu Paylaşan'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.CharField(choices=[('saniyə', 'saniyə'), ('dəqiqə', 'dəqiqə'), ('saat', 'saat'), ('gün', 'gün')], default='dəqiqə', max_length=10, null=True, verbose_name='Zaman Ölçüsü'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Youtube Linki'),
        ),
        migrations.AlterUniqueTogether(
            name='recipebook',
            unique_together={('owner', 'recipe')},
        ),
    ]
