# Generated by Django 4.0.6 on 2022-10-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_bio'),
        ('recipes', '0016_alter_blog_options_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'recipe')},
        ),
    ]
