# Generated by Django 4.0.6 on 2022-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Aktivlik'),
        ),
    ]
