# Generated by Django 4.0.6 on 2022-10-18 20:50

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_blog_description_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
