# Generated by Django 4.0.6 on 2022-10-18 20:52

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_quill.fields.QuillField(verbose_name='Açıqlama'),
        ),
    ]
